/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SkillsImport } from './routes/skills'
import { Route as MissionImport } from './routes/mission'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutmeImport } from './routes/aboutme'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SkillsRoute = SkillsImport.update({
  path: '/skills',
  getParentRoute: () => rootRoute,
} as any)

const MissionRoute = MissionImport.update({
  path: '/mission',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutmeRoute = AboutmeImport.update({
  path: '/aboutme',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/aboutme': {
      preLoaderRoute: typeof AboutmeImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/mission': {
      preLoaderRoute: typeof MissionImport
      parentRoute: typeof rootRoute
    }
    '/skills': {
      preLoaderRoute: typeof SkillsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutmeRoute,
  ContactRoute,
  MissionRoute,
  SkillsRoute,
])

/* prettier-ignore-end */
